In [1]:
import numpy as np

In [3]:
a=np.arange(10,22).reshape((3,4))

In [4]:
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [8]:
print("each element of the array is:")
for x in np.nditer(a):
    print(x, end="/")

each element of the array is:
10/11/12/13/14/15/16/17/18/19/20/21/