In [2]:
import numpy as np
a= [10,20,20,30,40,50]
print(a)
aa=np.array(a)
aa

[10, 20, 20, 30, 40, 50]


array([10, 20, 20, 30, 40, 50])

Create a 3x3 matrix with values ranging from 2 to 10

In [3]:
x=np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [4]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
print("update th value to 11")
x[6]=11
x

update th value to 11


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

Write a NumPy program to create an array with values ranging from 12 to 38

In [7]:
x=np.arange(12,38)
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

Write a NumPy program to reverse an array (first element becomes last).

In [8]:
print("reverse")
x=x[::-1]
x

reverse


array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])